// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: container.sql

package schema

import (
	"context"
)

const getContainerByID = `-- name: GetContainerByID :one
SELECT id, name, status, dockerfile, created_at, updated_at FROM container
WHERE id = ?
`

func (q *Queries) GetContainerByID(ctx context.Context, id int64) (Container, error) {
	row := q.db.QueryRowContext(ctx, getContainerByID, id)
	var i Container
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.Dockerfile,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
