// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package schema

import (
	"time"
)

type Container struct {
	ID         int64     `db:"id" json:"id"`
	Name       string    `db:"name" json:"name"`
	Status     string    `db:"status" json:"status"`
	Dockerfile string    `db:"dockerfile" json:"dockerfile"`
	CreatedAt  time.Time `db:"created_at" json:"created_at"`
	UpdatedAt  time.Time `db:"updated_at" json:"updated_at"`
}

type File struct {
	ID          int64     `db:"id" json:"id"`
	ContainerID int64     `db:"container_id" json:"container_id"`
	Name        string    `db:"name" json:"name"`
	MimeType    string    `db:"mime_type" json:"mime_type"`
	Content     []byte    `db:"content" json:"content"`
	Size        int64     `db:"size" json:"size"`
	CreatedAt   time.Time `db:"created_at" json:"created_at"`
	UpdatedAt   time.Time `db:"updated_at" json:"updated_at"`
}
